apiVersion: apps/v1
kind: Deployment
metadata:
  name: app7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app7
  template:
    metadata:
      labels:
        app: app7
    spec:
      containers:
      - name: app7
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "50Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
