apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  strategy :
    rollingUpdate:
      maxSurge: 1          # Create one extra replica only till update finishes.
      maxUnavailable: 1    # Allow max one instance to be unavailable
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "32Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
