apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 3

  selector:
    matchLabels:
      app: myapp1

  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp
        image: nginx:alpine

        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 3
            
        resources:
          limits:
            memory: "80Mi"
            cpu: "10m"
            
        ports:
        - containerPort: 80
