apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  ACCESS_TOKEN: MjNSVDNSVDNSM1QzUlQzVFRUVFRUMkdER0dESEhESkRK
  AUTH_URL: aHR0cDovL21haGVuZHJhLmNvbS9hcGkvb2F1dGg=

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: c2
    image: nginx:alpine
    envFrom:
      - secretRef:
          name: mysecret
    resources:
      limits:
        memory: "50Mi"
        cpu: "10m"
    ports:
      - containerPort: 80